fix: Set correct dependency configuration (#607)
This PR combines unrelated changes to limit the number of releases. The
main change is [fix: Set Jackson dependencies to
api/implementation](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/95d78317b3000dbb9687fa2cde3d61f35b54a4a0)
which is necessary to fix downstream problems. The other changes are
minor fixes to remove linter warnings.

Changes:

- [fix: Set Jackson dependencies to
api/implementation](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/95d78317b3000dbb9687fa2cde3d61f35b54a4a0)
(should fix `NoClassDefFoundError` in `nva-cristin-service`)
- [fix: Add runtime dependency on
libs.lambda.log4j](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/a3804be94027a25ee4d35138e5f7113cb2128ea0)
(should fix `Unable to locate appender "Lambda" for logger config
"root"` error in `nva-cristin-service`)
- [fix: Avoid catching generic
exception](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/7a4cb068f6c40c895f6b57c270792c85f3c7ae06)
- [refactor: Remove override identical to the overridden
method](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/cd709613da7a7c213aa006c9df4c17a99b781081)
- [refactor: Replace java.util.Date with
java.time.Instant](https://github.com/BIBSYSDEV/nva-commons/pull/607/commits/f3a45e7605bc47bd8559e6ff37ae4938aeafbfb6)